.TH "Artigos" 3 "Fri Jan 14 2022" "Version Grupo 2" "Laboratório de Programação" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Artigos
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcodArtigo\fP"
.br
.ti -1c
.RI "char \fBartigo\fP [\fBSC\fP]"
.br
.ti -1c
.RI "double \fBmaoObra\fP"
.br
.ti -1c
.RI "double \fBcustosFixos\fP"
.br
.ti -1c
.RI "double \fBmargemLucro\fP"
.br
.ti -1c
.RI "int \fBtamanhos\fP [2]"
.br
.ti -1c
.RI "double \fBdefaultPreco\fP"
.br
.ti -1c
.RI "double \fBincrementoPreco\fP"
.br
.ti -1c
.RI "bool \fBestado\fP"
.br
.ti -1c
.RI "double \fBtamanhoPreco\fP [15][2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBdefinitions\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "char artigo[\fBSC\fP]"

.PP
Definition at line \fB22\fP of file \fBdefinitions\&.h\fP\&.
.SS "int codArtigo"

.PP
Definition at line \fB21\fP of file \fBdefinitions\&.h\fP\&.
.SS "double custosFixos"

.PP
Definition at line \fB24\fP of file \fBdefinitions\&.h\fP\&.
.SS "double defaultPreco"

.PP
Definition at line \fB27\fP of file \fBdefinitions\&.h\fP\&.
.SS "bool estado"

.PP
Definition at line \fB29\fP of file \fBdefinitions\&.h\fP\&.
.SS "double incrementoPreco"

.PP
Definition at line \fB28\fP of file \fBdefinitions\&.h\fP\&.
.SS "double maoObra"

.PP
Definition at line \fB23\fP of file \fBdefinitions\&.h\fP\&.
.SS "double margemLucro"

.PP
Definition at line \fB25\fP of file \fBdefinitions\&.h\fP\&.
.SS "double tamanhoPreco[15][2]"

.PP
Definition at line \fB30\fP of file \fBdefinitions\&.h\fP\&.
.SS "int tamanhos[2]"

.PP
Definition at line \fB26\fP of file \fBdefinitions\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Laboratório de Programação from the source code\&.
