.TH "Clientes" 3 "Fri Jan 14 2022" "Version Grupo 2" "Laboratório de Programação" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Clientes
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcodCliente\fP"
.br
.ti -1c
.RI "char \fBnome\fP [\fBSC\fP]"
.br
.ti -1c
.RI "int \fBnif\fP"
.br
.ti -1c
.RI "char \fBpais\fP [\fBSC\fP]"
.br
.ti -1c
.RI "bool \fBestado\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBdefinitions\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int codCliente"

.PP
Definition at line \fB13\fP of file \fBdefinitions\&.h\fP\&.
.SS "bool estado"

.PP
Definition at line \fB17\fP of file \fBdefinitions\&.h\fP\&.
.SS "int nif"

.PP
Definition at line \fB15\fP of file \fBdefinitions\&.h\fP\&.
.SS "char nome[\fBSC\fP]"

.PP
Definition at line \fB14\fP of file \fBdefinitions\&.h\fP\&.
.SS "char pais[\fBSC\fP]"

.PP
Definition at line \fB16\fP of file \fBdefinitions\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Laboratório de Programação from the source code\&.
