.TH "colors.c" 3 "Fri Jan 14 2022" "Version Grupo 2" "Laboratório de Programação" \" -*- nroff -*-
.ad l
.nh
.SH NAME
colors.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include 'definitions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBwhite\fP ()"
.br
.RI "Permite o uso de 'output' colorido\&. "
.ti -1c
.RI "void \fBred\fP ()"
.br
.ti -1c
.RI "void \fBgreen\fP ()"
.br
.ti -1c
.RI "void \fBblue\fP ()"
.br
.ti -1c
.RI "void \fByellow\fP ()"
.br
.ti -1c
.RI "void \fBpurple\fP ()"
.br
.ti -1c
.RI "void \fBbold\fP ()"
.br
.ti -1c
.RI "void \fBboldRed\fP ()"
.br
.ti -1c
.RI "void \fBcyan\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void blue ()"

.PP
Definition at line \fB24\fP of file \fBcolors\&.c\fP\&.
.SS "void bold ()"

.PP
Definition at line \fB39\fP of file \fBcolors\&.c\fP\&.
.SS "void boldRed ()"

.PP
Definition at line \fB44\fP of file \fBcolors\&.c\fP\&.
.SS "void cyan ()"

.PP
Definition at line \fB49\fP of file \fBcolors\&.c\fP\&.
.SS "void green ()"

.PP
Definition at line \fB19\fP of file \fBcolors\&.c\fP\&.
.SS "void purple ()"

.PP
Definition at line \fB34\fP of file \fBcolors\&.c\fP\&.
.SS "void red ()"

.PP
Definition at line \fB14\fP of file \fBcolors\&.c\fP\&.
.SS "void white ()"

.PP
Permite o uso de 'output' colorido\&. 
.PP
Definition at line \fB9\fP of file \fBcolors\&.c\fP\&.
.SS "void yellow ()"

.PP
Definition at line \fB29\fP of file \fBcolors\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Laboratório de Programação from the source code\&.
