.TH "main.c" 3 "Fri Jan 14 2022" "Version Grupo 2" "Laboratório de Programação" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdbool\&.h>\fP
.br
\fC#include 'definitions\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.RI "Função Main do programa\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBNC\fP = \-1"
.br
.ti -1c
.RI "int \fBNA\fP = \-1"
.br
.ti -1c
.RI "int \fBNE\fP = \-1"
.br
.ti -1c
.RI "\fBClientes\fP * \fBcliente\fP"
.br
.ti -1c
.RI "\fBArtigos\fP * \fBartigo\fP"
.br
.ti -1c
.RI "\fBEncomendas\fP * \fBencomenda\fP"
.br
.ti -1c
.RI "\fBRuntime\fP * \fBruntime\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.PP
Função Main do programa\&. Ficheiro \fBmain\&.c\fP\&.
.PP
\fBNote\fP
.RS 4
tipoUtilizador - valores possiveis: 1 - Cliente, 2 - Administrador ou 0 - Sair 
.PP
Esta é a primeira função a ser executada 
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBmain\&.c\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBArtigos\fP* artigo"

.PP
Definition at line \fB20\fP of file \fBmain\&.c\fP\&.
.SS "\fBClientes\fP* cliente"

.PP
Definition at line \fB19\fP of file \fBmain\&.c\fP\&.
.SS "\fBEncomendas\fP* encomenda"

.PP
Definition at line \fB21\fP of file \fBmain\&.c\fP\&.
.SS "int NA = \-1"

.PP
Definition at line \fB16\fP of file \fBmain\&.c\fP\&.
.SS "int NC = \-1"

.PP
Definition at line \fB15\fP of file \fBmain\&.c\fP\&.
.SS "int NE = \-1"

.PP
Definition at line \fB17\fP of file \fBmain\&.c\fP\&.
.SS "\fBRuntime\fP* runtime"

.PP
Definition at line \fB22\fP of file \fBmain\&.c\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Laboratório de Programação from the source code\&.
