.TH "md__r_e_a_d_m_e" 3 "Fri Jan 14 2022" "Version Grupo 2" "Laboratório de Programação" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- final project of programming laboratory 

.SH "compile and run the project"
.PP
.SH "gcc \&.\\main\&.c \&.\\administrador\&.c \&.\\shopping\&.c \&.\\colors\&.c \&.\\queries\&.c \&.\\clientes\&.c \&.\\util\&.c -o main && \&.\\main"
.PP

