.TH "Runtime" 3 "Fri Jan 14 2022" "Version Grupo 2" "Laboratório de Programação" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Runtime
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <definitions\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcurrentClient\fP"
.br
.ti -1c
.RI "char \fBstringDesconto\fP [7]"
.br
.ti -1c
.RI "double \fBpercentageDesconto\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB47\fP of file \fBdefinitions\&.h\fP\&.
.SH "Field Documentation"
.PP 
.SS "int currentClient"

.PP
Definition at line \fB48\fP of file \fBdefinitions\&.h\fP\&.
.SS "double percentageDesconto"

.PP
Definition at line \fB50\fP of file \fBdefinitions\&.h\fP\&.
.SS "char stringDesconto[7]"

.PP
Definition at line \fB49\fP of file \fBdefinitions\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Laboratório de Programação from the source code\&.
